services:
  # Portainer Service
  agent:
    # Use the portainer/agent Docker image
    image: portainer/agent
    restart: unless-stopped
    container_name: agent
    volumes:
      # Mount the host's Docker socket into the container
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the host's Docker volumes into the container
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - monitoring
      - proxy
    ports:
      - 9001:9001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agent.entrypoints=http"
      - "traefik.http.routers.agent.rule=Host(`portainer.rocinante.mangolabs.internal`)"
      - "traefik.http.middlewares.agent-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.agent.middlewares=agent-https-redirect"
      - "traefik.http.routers.agent-secure.entrypoints=https"
      - "traefik.http.routers.agent-secure.rule=Host(`portainer.rocinante.mangolabs.internal`)"
      - "traefik.http.routers.agent-secure.tls=true"
      - "traefik.http.routers.agent-secure.service=agent"
      - "traefik.http.services.agent.loadbalancer.server.port=9001"
      - "traefik.docker.network=proxy"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro \
      - /sys:/sys:ro \
      - /var/lib/docker/:/var/lib/docker:ro \
      - /dev/disk/:/dev/disk:ro \
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cadvisor.entrypoints=http"
      - "traefik.http.routers.cadvisor.rule=Host(`contmetrics.rocinante.mangolabs.internal`)"
      - "traefik.http.middlewares.cadvisor-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.cadvisor.middlewares=cadvisor-https-redirect"
      - "traefik.http.routers.cadvisor-secure.entrypoints=https"
      - "traefik.http.routers.cadvisor-secure.rule=Host(`contmetrics.rocinante.mangolabs.internal`)"
      - "traefik.http.routers.cadvisor-secure.tls=true"
      - "traefik.http.routers.cadvisor-secure.service=cadvisor"
      - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    ports:
      - 8080:8080
    networks:
      - proxy
      - monitoring
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - proxy
      - monitoring
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./Monitoring/Prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cadvisor.entrypoints=http"
      - "traefik.http.routers.cadvisor.rule=Host(`prometheus.rocinante.mangolabs.internal`)"
      - "traefik.http.middlewares.cadvisor-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.cadvisor.middlewares=cadvisor-https-redirect"
      - "traefik.http.routers.cadvisor-secure.entrypoints=https"
      - "traefik.http.routers.cadvisor-secure.rule=Host(`prometheus.rocinante.mangolabs.internal`)"
      - "traefik.http.routers.cadvisor-secure.tls=true"
      - "traefik.http.routers.cadvisor-secure.service=prometheus"
      - "traefik.http.services.cadvisor.loadbalancer.server.port=9090"
      - "traefik.docker.network=proxy"
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./Monitoring/Grafana/config/datasources:/etc/grafana/provisioning/datasources/
    ports:
      - "9100:3000"
    networks:
      - monitoring
networks:
  monitoring:
    name: monitoringNetwork
  proxy:
    external: true
