services:
  reverse-proxy:
    image: traefik:v2.10
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # -- (Optional) Enable Dashboard, don't do in production
      - 8082:8080
    # -- (Optional) When using a custom network
    networks:
      - proxy
    volumes:
      # Change where you store your config files
      - /etc/localtime:/etc/localtime:ro
      - ./Traefik/config/traefik.yml:/traefik.yml:ro
      - ./Traefik/config/acme.json:/acme.json
      - ./Traefik/config/config.yml:/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # -- (Optional) When using Cloudflare as Cert Resolver
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`${SUBDOMAIN_NAME}.${DOMAIN_NAME}`)"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`${SUBDOMAIN_NAME}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=${SUBDOMAIN_NAME}.${DOMAIN_NAME}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.${DOMAIN_NAME}"
      - "traefik.http.routers.traefik-secure.service=api@internal"
networks:
  proxy:
    external: true
